### ISSUE TITLE
Not processing, oneplus-3t 

### ISSUE THREAD

**Issue by NOUSHADPOTTIPPARA** [ShadySquirrel/ViPER4Android#5] opened 2017-10-24 18:11 UTC
I have a problem, on my
oneplus-3t, model no oneplus A3003, oxygen os 4.5.0. Android 7.1.1, build number - oneplus A3003_28_170923.

It is not processing

Magisk version 14
Magisk manager version 5.4.0
Using latest module

Driver status:
Driver Version: 2.5.0.4
NEON Enabled: Yes
Enabled: Yes
Status: Normal
Audio Format: Supported
Processing: No
Sampling Rate: 48000

Please address sir

**Comment by ShadySquirrel** [comment] 2017-10-24 19:28
If 'Processing: No' is shown while there is no playback, it's okay. If it says no while playback is active, I'd need some logs and files.

**Comment by NOUSHADPOTTIPPARA** [comment] 2017-10-25 03:23
There was play back sir, but it's not processing

**Comment by NOUSHADPOTTIPPARA** [comment] 2017-10-25 03:35
I use jio music and poweramp. Not processing on both. Tried direct volume control on and off in poweramp. No luck...

**Comment by NOUSHADPOTTIPPARA** [comment] 2017-10-25 03:36
Please let me know which logs and files you need

**Comment by ShadySquirrel** [comment] 2017-10-25 09:54
I don't know about jio player, but Poweramp has it's own DSP, and V4A will work with it only in compatibility mode. Try with different player (Black player, GPM etc.). Also, if your system has different effects/equaliser, you'll have to set V4A as default one or disable original app.

**Comment by NOUSHADPOTTIPPARA** [comment] 2017-10-25 10:01
I will check and report sir

**Comment by NOUSHADPOTTIPPARA** [comment] 2017-10-25 10:46
![Screenshot](https://i.imgur.com/nBAtWkz.jpg)


Black player running,but v4a not processing

**Comment by ShadySquirrel** [comment] 2017-10-25 11:46
Ok, I need this:
- do you have any other audio mods installed?
- copy of audio_effects.conf file
- did it work with older version?

**Comment by NOUSHADPOTTIPPARA** [comment] 2017-10-25 12:02
1. I have only this module installed.
2

3. I didn't try the older version. I flashed this module directly from
magisk. There is another app - viper4android FX  v2. 3.4.0, v1.2 which also
had the very same issue.

**Comment by NOUSHADPOTTIPPARA** [comment] 2017-10-25 12:07
Can you please send your mail id so that I can send audio_effects.conf file?

**Comment by NOUSHADPOTTIPPARA** [comment] 2017-10-25 12:18
https://drive.google.com/file/d/0B3_KyzXS2bJgU0g3N2g1WnNLT29SMXhEelAtUXZfN2VRaGln/view?usp=drivesdk

**Comment by NOUSHADPOTTIPPARA** [comment] 2017-10-25 12:22
Please find the audio_effects.conf file

**Comment by ShadySquirrel** [comment] 2017-10-25 14:59
Please, use edit button instead of posting new comment.

I've reviewed your audio_effects.conf and found out this:
```
libraries {
  v4a_fx {
    path /system/lib/soundfx/libv4a_fx_ics.so
  }
  v4a_fx {
    path /system/lib/soundfx/libv4a_fx_ics.so
  }
  v4a_fx {
    path /system/lib/soundfx/libv4a_fx_ics.so
  }
...
effects {
  v4a_standard_fx {
    library v4a_fx
    uuid 41d3c987-e6cf-11e3-a88a-11aba5d5c51b
  }
  v4a_standard_fx {
    library v4a_fx
    uuid 41d3c987-e6cf-11e3-a88a-11aba5d5c51b
  }
  v4a_standard_fx {
    library v4a_fx
    uuid 41d3c987-e6cf-11e3-a88a-11aba5d5c51b
  }
```
Which is, when compared to my device, telling me that something went wrong or you had other sound mods installed before/parallel with mine, so you've ended with multiple V4A entries. Can you please uninstall the mod, and install it again? Otherwise, you'll have to edit audio_effects.conf file in module directory manually and remove multiplied entries.

**Comment by NOUSHADPOTTIPPARA** [comment] 2017-10-25 15:08
I will try. Thanks sir

**Comment by NOUSHADPOTTIPPARA** [comment] 2017-10-25 17:39
This is my new audio_effects.conf file after uninstalling the module from magisk
https://drive.google.com/file/d/0B3_KyzXS2bJgc2hTWi1pdUVFVVk/view?usp=drivesdk

**Comment by ShadySquirrel** [comment] 2017-10-25 17:45
That's okay. Now install the module and check if multiplicated V4A entries are there again.

**Comment by NOUSHADPOTTIPPARA** [comment] 2017-10-25 17:58
This is the new file after installing the module again
https://drive.google.com/file/d/0B3_KyzXS2bJgLVJRTVllSF9oalE/view?usp=drivesdk

Still same problem

**Comment by ShadySquirrel** [comment] 2017-10-25 18:04
Ok, now, does OxygenOS have it's own effects/equalizer? If so, disable them, or use Music effects configuration option in Settings -> Sound.

**Comment by NOUSHADPOTTIPPARA** [comment] 2017-10-25 18:25
Default equalizer is disabled and v4a is enabled in app.

**Comment by ShadySquirrel** [comment] 2017-10-25 19:29
And still no output from V4A? Can you check if your OS has more than one audio_effects file?

**Comment by NOUSHADPOTTIPPARA** [comment] 2017-10-26 02:09
I have only 1 audio_effects.conf file and another audio policy file. Here is the link

https://drive.google.com/file/d/0B3_KyzXS2bJgM2pwN09Ja3lLOEk/view?usp=drivesdk

**Comment by NOUSHADPOTTIPPARA** [comment] 2017-10-26 06:56
Do I need busy box to be installed?

**Comment by NOUSHADPOTTIPPARA** [comment] 2017-10-26 07:38
I updated the module from magisk and i have found TWO ✌️ audio_effects.conf files.

1. system/etc/audio_effects.conf

https://drive.google.com/file/d/0B3_KyzXS2bJgQlV6di1IS2ZwWFU/view?usp=drivesdk

2. system/vendor/etc/audio_effects.conf 

https://drive.google.com/file/d/0B3_KyzXS2bJgbTduN2IxZVEtSEE/view?usp=drivesdk


Please address sir

**Comment by ShadySquirrel** [comment] 2017-10-26 09:27
Everything okay there. Still, no real reason why V4A won't work. That's all that this module changes: audio_effects.conf (all of them, if OOS doesn't have something more specific I don't know about), mounts app and library, injects sepolicy. All of those are working fine, so it probably is something within OOS.

**Comment by hexian000** [comment] 2017-10-26 10:31
I used to have same problem on OOS.
OOS for OnePlus3T has Dirac Sound module, removing it first.

**Comment by ShadySquirrel** [comment] 2017-10-26 10:40
@hexian000 can you give me apk name (or whatever it is?). I may want to automatically remove it/replace it.
@NOUSHADPOTTIPPARA try running V4A in compatibility mode.

**Comment by NOUSHADPOTTIPPARA** [comment] 2017-10-26 10:41
Please specify how to remove it hexian000

**Comment by NOUSHADPOTTIPPARA** [comment] 2017-10-26 10:42
@hexian000 please specify how to remove it.

**Comment by hexian000** [comment] 2017-10-26 10:57
/system/app/DiracAudioControlService/DiracAudioControlService.apk
/system/app/DiracManager/DiracManager.apk
this is apk name, if you have (root access) or (custom recovery), you can remove these directorys
@ShadySquirrel @NOUSHADPOTTIPPARA

**Comment by NOUSHADPOTTIPPARA** [comment] 2017-10-26 11:04
@ShadySquirrel i have tried many times sir

**Comment by NOUSHADPOTTIPPARA** [comment] 2017-10-26 11:05
@hexian000 delete these 2 apks?

**Comment by ShadySquirrel** [comment] 2017-10-26 11:06
I'll probably make my module do it for you, stay tuned.
Until that, you'll have to remove it manually.

If removing those files solves the issue, can I close this now?

**Comment by hexian000** [comment] 2017-10-26 11:08
/system/app/DiracAudioControlService
/system/app/DiracManager
@NOUSHADPOTTIPPARA remove these two directorys and reboot, if anything go wrong, dirty flash OOS will restore everything.

**Comment by NOUSHADPOTTIPPARA** [comment] 2017-10-26 11:10
@hexian000 Will try friend. @ShadySquirrel thanks for your valuable time sir

**Comment by ShadySquirrel** [comment] 2017-10-26 11:14
Leave answer if removing those files fixed this issue for you, so I could close this and mark it as solved (and start working on module-implemented fix)

**Comment by NOUSHADPOTTIPPARA** [comment] 2017-10-26 11:32
Ok Sir

**Comment by ShadySquirrel** [comment] 2017-10-26 11:35
Before you mod your system, try with module version from this comment. I've added Dirac folders to the replace list.
[viper4android_v40_magisk_v14_oosfix.zip.zip](https://github.com/ShadySquirrel/ViPER4Android/files/1418138/viper4android_v40_magisk_v14_oosfix.zip.zip)

**Comment by NOUSHADPOTTIPPARA** [comment] 2017-10-26 12:09
Ok

**Comment by NOUSHADPOTTIPPARA** [comment] 2017-10-26 13:48
I tried this also, no luck. I removed the above mentioned directories, rebooted, no luck.

For your information - - -

I was using v4a arise, by Arise magnum opus by flashing a zip file on my previous oos version. I had my own effect profiles saved in that version named 'earphone' and 'car' . Then the os update came, i downloaded and CLEAN FLASHED the rom. 

Now after installing this module my effect profiles are available in this v4a too, strangely.. Means something is there even after a clean flash...

**Comment by ShadySquirrel** [comment] 2017-10-26 14:05
Well, profiles are there because your data was saved during flashing, and V4A app in module is same one officially distributed in V4A thread, so that's why you still have your profiles.

I'm more interested in what OnePlus changed to stop this thing from working there...

**Comment by NOUSHADPOTTIPPARA** [comment] 2017-10-26 14:38
I removed the module, rebooted, deleted the directories, flashed the module. No luck.

Please note:
1.I have no busy box installed
2. Viper never asked for root permissions hence not granted the same

**Comment by hexian000** [comment] 2017-10-27 04:55
Since I updated OP3T to the latest OOS, removing Dirac isn't working for me either. :(
Viper4Arise is still working.
Wondering why.
p.s. This module works very well on OOS for OP5, no busybox installation needed(magisk has a private one)

**Comment by NOUSHADPOTTIPPARA** [comment] 2017-10-27 04:59
@hexian000 viper4Arise is also not working on OOS 4.5.0, there was no problem with beta builds.

Magnum opus finishes flashing in recovery and occupies around 100 mb, but the app - v4arise- is not shown anywhere on OOS 4.5.0. It was fine in open beta builds

**Comment by ShadySquirrel** [comment] 2017-10-27 15:24
Since I don't own OP3/3T, can someone of you post a solution for that issue, if found anytime? I'd like to incorporate it into module.

**Comment by pikatchu2k3** [comment] 2017-11-09 11:07
@ShadySquirrel
Unfortunately I have now the same problem. 
I wiped and resetup my device. The difference to my previous config is just an update on my rom to the newest version (21.10.17 updated to 26.10.17)

I tried to collect some logs for you. 

Device Axon 7
Resurrection remix 7.1.2 26.10.17 build 
Stock kernel (before I used a custom kernel)
Viper4android doesn't work on normal or compatible mode 
Uninstalled audio fx 
Magisk 14.3 (tried also deactivating other modules) 
Used modules iyoutube and greenify for Magisk. 


https://www.sendspace.com/file/djlk0y

**Comment by ShadySquirrel** [comment] 2017-11-09 12:26
I will have to ask you to open a new issue following [this guide](https://github.com/ShadySquirrel/ViPER4Android#support)

**Comment by pikatchu2k3** [comment] 2017-11-09 12:54
Even if my problem is the same as the OP? 

Surely I will do I it.

**Comment by ShadySquirrel** [comment] 2017-11-09 13:07
Different devices, and probably different issue - OP3/3T issue is connected with Dirac audio, yours may be different.

**Comment by ShadySquirrel** [comment] 2017-12-13 22:24
No news for a month now, I'm closing this.

**Closed by ShadySquirrel** 2017-12-13 22:24 UTC
Labels: bug, help wanted

**Comment by NateDev100** [comment] 2017-12-17 19:31
Wait, so was a fix ever found for this? lol

**Comment by ShadySquirrel** [comment] 2017-12-17 19:37
Well, one way is to find a way how to actually remove/disable Dirac and do it manually for testing, before I include that in module. I can't do that because I have no devices actually using it; other way is to wait for V4A devs to do something about it (slim chances, tbh), and third possibility is to try running V4A in compatibility mode and hope for the best (there was some success [here](#13))

**Comment by Patryk122PL** [comment] 2018-01-18 12:34
Hello, I have Oneplus 3T and I can confirm that your modification "viper4android_v40_magisk_v14_oosfix.zip.zip" actually works! I can't say why it didn't work for hexian000, but here is the things I've done to make it work:

I'm running OOS 4.1.6 (custom build, but nothing significant was changed, mostly debloat) with Magisk 15.3 and to test this module I've used Spotify.

1. Installed ViPER4Android Magisk module v5 from magisk app (dirac off, but present on the device) - not working.
2. Installed deep_bufer remover - no luck.
3. Disabled Dirac App and service via Titanium Backup - nope.
4. Found this page, re-enebled dirac app & service, uninstalled your Viper magisk module.
5. Installed modified version of Viper magisk module from this page - SUCESS! Works like a charm!

Of course every module modification was followed by a device restart.
In settings > audio there is no eq configuration option anymore and dirac app & service is removed, which is good.

If there is something else you want to know I would be glad to help.

**Comment by ShadySquirrel** [comment] 2018-01-18 12:43
Thank you for report, I'd add Dirac folders from that quick-fix to one of future versions, like I already did for AudioFX and MusicFX in [this commit](https://github.com/ShadySquirrel/ViPER4Android/commit/4734a5e89ff8b148d4ac4dabe316595238909c3a).

For reference, can you try module version 5.1? It's reported to fix issues on OnePlus 5, maybe it will help with 3T, too.

**Comment by Patryk122PL** [comment] 2018-01-18 12:49
Yes I've tried version 5.1. It didn't work for me. I updated my comment to fix this typo (I meant v5.1)

**Comment by ShadySquirrel** [comment] 2018-01-18 12:51
Ok, thank you for the input!

There will be a new version of module, as soon as I get some reports about Pixel 8.1 issue I'm trying to fix.

**Comment by Patryk122PL** [comment] 2018-01-18 13:03
Thank you!
I'll share my feedback when the new version will be available.

**Comment by ShadySquirrel** [comment] 2018-01-21 18:20
@Patryk122PL can you please test sepolicy change mentioned in #18 and #19, but with regular module, not one including disabled Dirac?

**Comment by Patryk122PL** [comment] 2018-01-21 19:09
I've added
`magiskpolicy --live "allow hal_audio_default hal_audio_default_tmpfs file { execute }"`
to `/magisk/viper4android/post-fs-data.sh` and it didn't work. After first reboot my log had couple of denied access in audit, but after second only something like "type=1400" etc. Strange..

Version v5.2 also don't work for me and audit denied is back.
[audit.log.txt](https://github.com/ShadySquirrel/ViPER4Android/files/1650083/audit.log.txt)

**Comment by ShadySquirrel** [comment] 2018-01-22 07:13
You're still on Nougat, right?

**Comment by Patryk122PL** [comment] 2018-01-22 07:44
Yes. OxygenOS 4.1.6 is an Android 7.1.1

**Comment by ShadySquirrel** [comment] 2018-01-22 08:59
Ok thanks, I'll check it as soon as I'm on my PC.

**Comment by Patryk122PL** [comment] 2018-01-25 08:47
Ok so it doesn't work neither in permissive SELinux nor with AudModLib installed. Here are some logs:

1. SELinux enforcing: 
[2018-01-25-09-17-45.txt](https://github.com/ShadySquirrel/ViPER4Android/files/1663194/2018-01-25-09-17-45.txt)
[magisk_log_20180125_092653.log](https://github.com/ShadySquirrel/ViPER4Android/files/1663195/magisk_log_20180125_092653.log)
2. SELinux permissive:
[2018-01-25-09-27-01.txt](https://github.com/ShadySquirrel/ViPER4Android/files/1663197/2018-01-25-09-27-01.txt)
[magisk_log_20180125_092653.log](https://github.com/ShadySquirrel/ViPER4Android/files/1663198/magisk_log_20180125_092653.log)
3. SELinux permissive & AudModLib installed:
[2018-01-25-09-31-05.txt](https://github.com/ShadySquirrel/ViPER4Android/files/1663200/2018-01-25-09-31-05.txt)
[magisk_log_20180125_093055.log](https://github.com/ShadySquirrel/ViPER4Android/files/1663201/magisk_log_20180125_093055.log)

**Comment by ShadySquirrel** [comment] 2018-01-25 11:25
You don't need AML for this module.

V4A is installed but it's not processing, right? Not even in compatibility mode? I couldn't find anything, no denials, no errors, nothing, V4A reports everything is great there. Looks like Dirac is main there and nothing can override it... But on newer devices with Dirac, it's all OK, which makes me wonder.

Does OP3T have any other audio_effects config file than ones in /system/etc and /vendor/etc?

**Comment by Patryk122PL** [comment] 2018-01-25 15:06
Well I've tested with AML just to be sure. Anyway V4A doesn't work in compatibility mode, permissive or enforcing selinux, neither with or without aml nor deep_buffer remover module, and audio_effects exist only in this two places you mentioned (etc and vendor/etc). Freezing dirac also doen't seem to make any difference. I'm so confused...
[2018-01-25-15-47-35.txt](https://github.com/ShadySquirrel/ViPER4Android/files/1664430/2018-01-25-15-47-35.txt) <- this show up in log after changing a song

**Comment by ShadySquirrel** [comment] 2018-01-25 19:49
I'm getting similar output, that's okay...

Are these:
```
/system/app/DiracAudioControlService
/system/app/DiracManager
```
Only present dirac paths?

**Comment by Patryk122PL** [comment] 2018-01-25 21:37
Yes. There is also a file called 
`/system/vendor/etc/diracvdd.bin` 
but I have no idea what it's for

**Comment by ShadySquirrel** [comment] 2018-01-25 21:42
That's probably firmware or calibration file.

[Can you try this one for me?](https://github.com/ShadySquirrel/ViPER4Android/files/1665767/viper4android_v521_magisk_v15.zip)

**Comment by Patryk122PL** [comment] 2018-01-25 22:24
Sadly it doesn't work, but I found on xda modules configured for OxygenOS 4.1.6 and this one works 
[magisk-viper4android_fx_2.3.4.0_shq_v2.1.zip](https://github.com/ShadySquirrel/ViPER4Android/files/1665890/magisk-viper4android_fx_2.3.4.0_shq_v2.1.zip) so maybe you can extract some configuration files out of it.

**Comment by ShadySquirrel** [comment] 2018-01-25 22:30
Hm, weird thing, I just added Dirac paths from above to replace list.

That module is overriding your effects configuration completely, I'd rather avoid using it, TBH.

Can you pull effect config files without my module installed?

**Comment by Patryk122PL** [comment] 2018-01-25 22:45
I don't know what you mean by "completely overriding", because with this version enabled and effects applied I can still change settings in dirac app and they take place. Anyway cfg files: 
[audio_effects.zip](https://github.com/ShadySquirrel/ViPER4Android/files/1665949/audio_effects.zip)

**Comment by ShadySquirrel** [comment] 2018-01-25 22:48
By completely overriding I mean it's using it's own config files, instead editing yours. I'll compare the differences now

**Comment by Patryk122PL** [comment] 2018-01-25 23:05
Probably true... I'll try a few tweaks.. see if something changes.
