### ISSUE TITLE
Not working on N6P 8.0.0

### ISSUE THREAD

**Issue by NickNothom** [ShadySquirrel/ViPER4Android#3] opened 2017-10-19 17:13 UTC
Hello,
This isn't working for me on a Nexus 6P with 8.0.0. Build Number OPR6.170623.019. Magisk 14.0. Enabling / disabling / changing settings has zero effect on the sound. Using ATH-M50X headphones over aux. 

Driver status:
Version: 2.5.0.4
NEON Enabled: Yes
Enabled: Yes
Status: Normal
Audio Format: Supported
Processing: No
Sampling Rate: 48000

If you don't support Oreo yet, or this isn't the right place to post this, feel free to delete / close.

**Comment by ShadySquirrel** [comment] 2017-10-19 19:27
I can't support Oreo before official V4A :) But I can check official thread and see if some changes are needed to make it work and make a test module for you, my device is still on Nougat.

**Comment by NOUSHADPOTTIPPARA** [comment] 2017-10-24 18:01
Me too have the same problem, on my
 oneplus-3t, model no oneplus A3003, oxygen os 4.5.0. Android 7.1.1, build number -  oneplus A3003_28_170923.
Driver status:
Driver Version: 2.5.0.4
NEON Enabled: Yes
Enabled: Yes
Status: Normal
Audio Format: Supported
Processing: No
Sampling Rate: 48000

**Comment by xstahsie** [comment] 2017-10-24 22:57
Hi,

Was Working fine on my Nexus 6P (running 8.0 OPR6.170623.013) until I updated the module to 2.5.0.5. 

Keeps force closing after the update.

**Comment by ShadySquirrel** [comment] 2017-10-24 23:01
I'm going to need a subversion, not 2.5.0.5. Main version follows V4A version.

**Comment by whezzel** [comment] 2017-10-25 06:57
I just updated to the new magisk module (21.10.2017) that uses the non-materialized version of the viper app. The viper app keeps force closing making my phone unusable until the module is disabled.

**Comment by whezzel** [comment] 2017-10-25 06:59
^Edit: this is on a N6p running Android 8.0

**Comment by ShadySquirrel** [comment] 2017-10-25 09:50
Do you have old module version? It looks like original V4A app doesn't work with Oreo properly (I'm still on Nougat) but materialized does. You can try clearing data and cache first.

**Comment by whezzel** [comment] 2017-10-25 09:57
I was on version 08.10.2017

If the original viper app doesn't work with Oreo, would you mind sending me
a copy of version 08.10.2017 with the materialized viper app? When I
downloaded the updated module it overwrote the old zip file on my phone.

--Zach

On Oct 25, 2017 4:50 AM, "I" <notifications@github.com> wrote:

Do you have old module version? It looks like original V4A app doesn't work
with Oreo properly (I'm still on Nougat) but materialized does. You can try
clearing data and cache first.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/ShadySquirrel/ViPER4Android/issues/3#issuecomment-339276681>,
or mute the thread

**Comment by ShadySquirrel** [comment] 2017-10-25 10:24
You have some older versions under "Releases" here.

**Comment by whezzel** [comment] 2017-10-27 12:24
Thanks for you comments on this. I was able to get it working with the materialized version on N6P running Android 8.0.0

Also, I can confirm the lastest "Release 4: 26.10.2017 Materialized" zip runs on the N6P Android 8.1.0 beta.

The new naming standard for zips is a great addition too.

Thanks for your work on this project.

**Comment by ShadySquirrel** [comment] 2017-10-27 15:22
No problem, it's my pleasure :D I'm glad Material version works on Oreo, who knows for how long we'd have to wait for official app to update...

I'm closing this and marking it as fixed.

**Closed by ShadySquirrel** 2017-10-27 15:22 UTC
Labels: bug, help wanted
